# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 10 Jul 2017 12:44:03 +0000
*               @ALL          1
*               @user         8
