<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 17 Jul 2017 12:23:39 +0200
 */

$conf['title'] = 'Studyguide';
$conf['lang'] = 'de';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['discussion']['automatic'] = 1;

// end auto-generated content
