<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 10 Jul 2017 14:52:04 +0200
 */

$conf['title'] = 'Studyguide';
$conf['lang'] = 'de';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
